# Generated by Django 3.1.5 on 2023-08-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countdown_core', '0008_auto_20210422_2343'),
        ('custom_user', '0010_auto_20210422_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bookmarked_countdowns',
            field=models.ManyToManyField(related_name='user_bookmarks', to='countdown_core.Countdown'),
        ),
    ]
